<?php

return [
    1 =>    'Arts',
    2 => 'Arts du cirque',
    3 => 'Biologie Ecologie',
    4 => 'Biotechnologies',
    5 => 'Création et culture design',
    6 => 'Création et innovation technologiques (CIT)',
    7 => 'Ecologie-agronomie-territoires-développement durable',
    8 => 'Education physique et sportive (EPS)',
    9 => 'Enseignement moral et civique',
    10 => 'Enseignement scientifique',
    11 => 'Enseignement technologique transversal (ETT)',
    12 => 'Français',
    13 => 'Hippologie et équitation',
    14 => 'Histoire - Géographie',
    15 => 'Histoire-géographie, géopolitique et sciences politiques',
    16 => 'Humanités, littérature et philosophie',
    17 => 'Langues et cultures de l’Antiquité : latin ou grec',
    18 => 'Langues vivantes',
    19 => 'Langues, littératures et cultures étrangères et régionales',
    20 => 'Littérature et langues et cultures de l’Antiquité',
    21 => 'Management et gestion',
    22 => 'Mathématiques',
    23 => 'Numérique et sciences informatiques (NSI)',
    24 => 'Physique-chimie',
    25 => 'Principes fondamentaux de l’économie et de la gestion',
    26 => 'Santé et social',
    27 => 'Sciences de la vie et de la Terre (SVT)',
    28 => 'Sciences de l’ingénieur',
    29 => 'Sciences et laboratoire',
    30 => 'Sciences et techniques du théâtre, de la musique et de la danse (S2TMD)',
    31 => 'Sciences et technologies de laboratoire (STL)',
    32 => 'Sciences et technologies de l’hôtellerie et de la restauration (STHR)',
    33 => 'Sciences et technologies de l’industrie et du développement durable (STI2D)',
    34 => 'Sciences et technologies du design et des arts appliqués (STD2A)',
    35 => 'Sciences et technologies du management et de la gestion (STMG)',
    36 => 'Sciences numériques et technologie (SNT)',
    37 => 'Sciences économiques et sociales (SES)',
    38 => "Autre (préciser dans la biographie)"
];
